### ISSUE TITLE
検索ブロック: 「ボタンのみ」スタイルへの対応 #371

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#119]
初期表示はボタンのみで、ボタンをクリックするとテキスト入力欄が表示されるスタイルが増えています。

現状のフロントエンドでの動作

https://github.com/loos/arkhe/assets/54422211/1fa3967b-0af9-45b6-a989-1f2364603dc7

**Comment by ddryo** [comment]
コア側での修正を待ちます。
