### ISSUE TITLE
wp_enqueue_style でブラウザワーニングエラーが発生する

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#120]
ブロックのapiVersionが全てv3の場合、投稿エディターがiframe化されるようになりました。なので、apiVersion2のブロックプラグイン等を特に入れていない場合はiframe化され、以下のようなエラーが発生します。

```
arkhe-editor-css was added to the iframe incorrectly. Please use block.json or enqueue_block_assets to add styles to the iframe. 
```

ただちに影響はありませんが、以下のようにWPバージョンによって `enqueue_block_assets` と `enqueue_block_editor_assets` を切り替えても良いかもしれません。（コードは未検証です。）

```php
if ( is_wp_version_compatible( '6.3' ) ) {
	add_action( 'enqueue_block_assets', 'my_enqueue' );
} else {
	add_action( 'enqueue_block_editor_assets', 'my_enqueue' );
}
```

**Comment by ddryo** [comment]
enqueue_block_assetsはフロントにも読み込まれるため、一旦何もせず動向を様子見してみます。
