### ISSUE TITLE
エディターのiframe化によっていくつかの変数値が上書きされる

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#126]
WP6.3より、全てのブロックがv3であった場合、投稿エディターがiframe化されます。例えばArkheテーマを使っていて、v2のブロックプラグインを入れていない場合などです。

またエディター側では、エディターの状態や画面幅になどによって、いくつかのCSS変数を上書きしていると思います。

例:

```php
@media (max-width: 1680px) {
	body:not(.is-fullscreen-mode),
	.edit-post-layout.is-sidebar-opened {
		--ark-alignwide_ex_width: 0px;
	}
}

@media (min-width: 782px) {
	body:not(.is-fullscreen-mode) {
		--ark-editor-100vw: calc(100vw - 160px);
	}
}
```

例えば `.is-fullscreen-mode` クラスは、ルートドキュメントの `body` タグには付与されますが、iframeエディター内の `body` タグには付与されません。そのため、設定がフルスクリーンであったとしても、iframeエディタ―内では「フルスクリーンではない」と判定され、関連するCSS変数が上書きされ、意図しないレイアウトになってしまいます。

### WP6.2

フルスクリーンモード**ではないの**で、`--ark-alignwide_ex_width` はデフォルトの `100px`

![alignwide_ex_width_6 2](https://github.com/loos/arkhe/assets/54422211/6b088899-0ef3-4312-857a-ba86020adcb9)

### WP6.3

iframeエディターのbodyタグには、フルスクリーンモードであっても `is-fullscreen-mode` クラスが付かないので、`body:not(.is-fullscreen-mode)` セレクタに合致してしまい、`--ark-alignwide_ex_width` や `--ark-editor-100vw` が フルスクリーン**ではない**ものとして上書きされてしまう。

![alignwide_ex_width_6 3](https://github.com/loos/arkhe/assets/54422211/0ab2b74e-2148-4668-b291-adc2c8fb38a1)

### 解決方法

良い方法が思いつかないのですが、例えば

- `is-fullscreen-mode`、`.is-sidebar-opended` クラスに依存しない
- JSで、ルートドキュメントのbodyタグにあるクラスを判別し、ドキュメント内のiframe > body に必要なクラスを付与する
- 何らかの機能をメタボックスとして追加する ([メタボックスがあればiframe化されない](https://github.com/WordPress/gutenberg/blob/1052456a23a5625bf6566118d4a26df37a8b1c2c/packages/edit-post/src/components/visual-editor/index.js#L360)ため)

などがあると思います。

**Comment by ddryo** [comment]
コンテナクエリの導入を検討してみます。
