### ISSUE TITLE
翻訳関数に関する警告

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#150]
WP 6.7では、翻訳の読み込みが早すぎる場合に警告が出るようになったようです。

https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

Arkheに関しては、この警告の原因になっているのは以下コードです。

https://github.com/loos/arkhe/blob/19d8a68609bb6a69da34ec0349af692fbc8a7594/inc/consts.php#L5

定数を使わずに「Note : 」を該当箇所に含めれば解決できると思います。

**Comment by ddryo** [comment]
ありがとうございます！
