### ISSUE TITLE
カラムブロック：レイアウトのズレ

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#20]
コアのスタイルが若干変更され、`margin-top: var(--ark-mt)` が当たるようになってしまった

![capture3](https://user-images.githubusercontent.com/54422211/149617052-d2eb67ed-4599-481e-b79b-8c41b0c36204.png)

![capture](https://user-images.githubusercontent.com/54422211/149616988-859efbc9-7325-4c37-bf4e-988c819bd995.png)

**Comment by t-hamano** [comment]
カラムブロックに新項目・新スタイルが追加された事も考慮して対応する。

See: https://github.com/loos/SWELL/issues/111

**Comment by t-hamano** [comment]
## プレビュー

### 「モバイルでは縦に並べる」がオン（実質WordPress5.8のスタイルと同じ）

https://user-images.githubusercontent.com/54422211/149910407-d056dc0c-72c8-4c59-a270-7e820713569f.mp4

### 「モバイルでは縦に並べる」がオフ（WordPress5.9向けのスタイル）
https://user-images.githubusercontent.com/54422211/149910383-c07f189d-e86a-4603-80f8-1f1854004d32.mp4

**Comment by ddryo** [comment]
僕の方でCSS調整加えます！
