### ISSUE TITLE
フォントサイズバリエーションが上書きされてしまっている

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#21]
See: https://github.com/loos/SWELL/issues/57

**Comment by t-hamano** [comment]
再確認した所、`add_theme_support('editor-font-sizes')`で指定したサイズをもとに、`--wp-preset--font-size--{slug}`に反映されている

![capture](https://user-images.githubusercontent.com/54422211/149919317-04613142-7d4e-457e-be09-9ffa1d887395.png)

Arkhe・SWELLとも5.9-RC2で確認しているが、SWELLの方は何故かeditor-font-sizesの値がCSS変数に反映されていない。
Arkheに関しては、RC3で確認し問題なければクローズします。

**Comment by t-hamano** [comment]
RC3で確認。
`add_theme_support('editor-font-sizes')で指定したサイズが、ブロックエディター・フロントエンドともに各フォントサイズに正しく反映されているため、クローズとします。

**Comment by ddryo** [comment]
> `add_theme_support('editor-font-sizes')で指定したサイズが、ブロックエディター・フロントエンドともに各フォントサイズに正しく反映されているため

んん、なんでテーマによって差があるんだ...

**Comment by t-hamano** [comment]
`add_theme_support('editor-font-sizes')`の書き方はSWELLとArkheで変わらないはずなんですが、なぜかArkheの方だけ反映されました。。
コアソースを追ってみないと分からないですが、デフォルトのCSS変数が上書きされる条件？があるのかもしれません

**Comment by ddryo** [comment]
> `add_theme_support('editor-font-sizes')で指定したサイズが、ブロックエディター・フロントエンドともに各フォントサイズに正しく反映されているため、クローズとします。

これなんですが、今見るとダメでした。（5.9-RC3）

<img width="885" alt="スクリーンショット 2022-01-23 16 06 54" src="https://user-images.githubusercontent.com/31400297/150668366-1a2a03fd-e6c2-4d61-b882-20e465c1575e.png">

あと追加で気になったのが、SWELLとフォントサイズ選択部分のUIが異なる点です...。

▼ SWELL
▼ SWELL
<img width="276" alt="スクリーンショット 2022-01-23 16 04 05" src="https://user-images.githubusercontent.com/31400297/150668387-53eb9bdc-71cd-4de7-b691-fd173d2ae5c3.png">

**Comment by ddryo** [comment]
Twenty Twentyでも異なりました...。

▼ TT1
<img width="276" alt="スクリーンショット 2022-01-23 16 11 59" src="https://user-images.githubusercontent.com/31400297/150668454-4e4622a9-688b-444d-b991-7b94d529d79f.png">

▼ TT2
<img width="280" alt="スクリーンショット 2022-01-23 16 10 45" src="https://user-images.githubusercontent.com/31400297/150668458-f9cb3b56-91ee-4691-b7a2-4b3dbf4aae7f.png">

**Comment by t-hamano** [comment]
@ddryo 

そこは確か、フォントバリエーションの数が6以上だと、自動的にプルダウンになると思います！

**Comment by ddryo** [comment]
あ、なるほどです！ｗ
