### ISSUE TITLE
ソーシャルリンクブロック：ボタン間の余白が若干異なる

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#25]
![capture](https://user-images.githubusercontent.com/54422211/149618685-f699a5fa-92c7-467d-89a9-1d15c2201ffd.png)

**Comment by t-hamano** [comment]
5.9では縦方向並びのレイアウト、複数行折り返しのON/OFFも追加されているので、それらも考慮の上スタイリングする。

**Comment by t-hamano** [comment]
ブロックに `.wp-container-XXXX` というクラスが付与され、そのセレクタに対してインラインCSSで `gap:0.5em` が設定されている。
importantでリセットします。

![arkhe](https://user-images.githubusercontent.com/54422211/149712805-74500935-6ec6-4e95-9e5f-700f20da8862.png)

**Comment by ddryo** [comment]
5.8までに合わせるのではなく、5.9からのgapを使う方に合わせるように変更しました。
