### ISSUE TITLE
子ブロックに全幅を設定するとコンテンツ幅をはみ出る

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#29]
サイドバーありのページで、子ブロックに全幅を設定するとコンテンツ幅をはみ出る

![capture](https://user-images.githubusercontent.com/54422211/149892987-5f237b40-c7c7-40a3-81e2-d76529d3332c.png)

**Comment by ddryo** [comment]
@t-hamano 
サイドバーありのページではそもそも全幅を使う必要がなく、変に使ってほしくないためあえて崩れるままにしていました。
（よく自覚なく全幅とかを設定してちょっとだけ崩れると不具合報告してくる人もいるので、大きく崩れたほうが気づきやすいかなという理由です）

また、サイドバーありなし・スマホ表示などを踏まえると全幅系はかなり複雑になってくるので（Arkheはまだかなりシンプルですが）、あとで僕の方で再検証・再検討しておきます。

**Comment by ddryo** [comment]
@t-hamano 

モバイル・タブレットで逆に意図しない表示になっていたため、revertしました

<img width="1411" alt="スクリーンショット 2022-01-24 1 34 55" src="https://user-images.githubusercontent.com/31400297/150688757-2b658ae9-e8a1-408b-83dd-6308cb804337.png">

**Comment by ddryo** [comment]
サイドバーありのときは全幅＞全幅にする必要がなく普通幅でいいので、無駄なCSS増やしたくなくてあえて壊れたままにしていましたが、

改めて見てみると 以下の部分を important にするだけでOKではあるので（たぶんimportant極力使いたくなくてやってなかった気がしますが）、そちらで対応しました。

```
	// サイドバーありの時、コンテンツエリアでは幅を制限
	[data-sidebar="on"] .l-main & {
		@include pc {
			left: 0 !important;
			width: 100% !important;
		}
	}
```

#### ▼ サイドバーなし
<img width="1439" alt="スクリーンショット 2022-01-24 1 51 46" src="https://user-images.githubusercontent.com/31400297/150689226-e6c1bf98-a1a3-495c-b45d-83a315c92c6b.png">


#### ▼ サイドバーあり
<img width="1409" alt="スクリーンショット 2022-01-24 1 52 11" src="https://user-images.githubusercontent.com/31400297/150689246-c39ad7e4-f75b-4014-b310-e841e7177d10.png">
