### ISSUE TITLE
ボタンブロック：幅指定が正しく適用されない

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#31]
block-gap変数を考慮したwidthになっているから。
block-gap変数の考慮はクラシックテーマでは不要だと思うので、5.8のスタイルで上書きします。

![タイトルなし](https://user-images.githubusercontent.com/54422211/150086286-f6d39037-5b19-42b9-a1cb-3e0703f5a230.png)

**Comment by ddryo** [comment]
逆に5.9からのCSSが変数を使うように調整します！

**Comment by ddryo** [comment]
問題点の整理

1. 親の buttons (`.wp-container-{id}`)に対して `gap: 0.5em;`がある。
2. 子の button の 幅の計算では`var(--wp--style--block-gap, 0.5em) `が使われる
3. クラシックテーマだと`--wp--style--block-gap`はフロントで出力されないので、`0.5em`で全体的に計算が合う
4. ただしエディター側ではクラシックテーマでは`--wp--style--block-gap`は`2em`に設定されているので、`1`の`0.5em`と合わずにずれが生じる。

推測（未検証）

- `1`で`0.5em`なのはクラシックテーマだから？
- 本来はtheme.jsonで設定された値が出て`--wp--style--block-gap`と同じ値になる？
- だとしたら、コア側のバグ

**Comment by ddryo** [comment]
取り急ぎ、テーマ側で.wp-block-buttonsで--wp--style--block-gapを定義して対応。
