### ISSUE TITLE
記事タイトル部のフォントの見え方が異なる

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#33]
以下issueと同じ問題だと思われる。

- https://github.com/loos/SWELL/issues/58

**Comment by t-hamano** [comment]
WordPress5.8の時点で、コアのスタイルに上書きされていたので、実質テーマ側のCSSはあたっていなかった。
そのためコアの変更に追従するものとし、テーマ側での対応は不要とします。

![capture](https://user-images.githubusercontent.com/54422211/150303332-909ecd47-57bb-4a39-a1fd-22a0a5337727.png)

**Comment by ddryo** [comment]
僕の環境だと5.8の時点ではテーマ側の指定が勝っていました。

<img width="340" alt="スクリーンショット 2022-01-23 16 53 11" src="https://user-images.githubusercontent.com/31400297/150669568-8d3fbd7e-0b10-417d-80a4-6c237ff79548.png">

ちょっと謎ですが、詳細度高めて置くようにします！
