### ISSUE TITLE
カレンダーブロック：デバイスプレビュー時のレイアウトズレ

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#66]
モバイルプレビュー時に、コンテナ幅をはみ出す。
WP5.9 / 6.0 で発生。
TT1では問題ないため、CSSの問題？

![calendar](https://user-images.githubusercontent.com/54422211/169646628-25889573-6809-4b6a-8ea1-24c44c264ca1.png)

**Comment by ddryo** [comment]
こちらはbox-sizingの問題の影響でした。
