### ISSUE TITLE
ギャラリーブロック：フロントエンドとエディターでスタイルが異なる

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#82]
- 画像間のギャップが異なる。
- 「 画像の切り抜き」をオンにした時に、エディター側で切り抜かれない。

## フロントエンド

![frontend](https://user-images.githubusercontent.com/54422211/197988827-c554ffb3-dad1-42a4-8ec7-a5e1f093b8e2.png)

## エディター

![editor](https://user-images.githubusercontent.com/54422211/197988814-7d3976f3-6558-458c-896c-ad6b3aab5ad9.png)

**Comment by ddryo** [comment]
gapに関してはコアがクラシックテーマを配慮していないことで差が生まれていたと思うので、6.0から確か修正待ちで放置しています。

**Comment by ddryo** [comment]
https://github.com/loos/SWELL/issues/256
