### ISSUE TITLE
ファイルブロック：ボタンスタイルが無くなった

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#83]
`.wp-block-file .wp-block-file__button` のスタイルが無くなった。
コアに追従するなら、何もしなくてもいいかもしれない。

## 6.0

![6 0](https://user-images.githubusercontent.com/54422211/197991584-0eafda93-3064-4642-8b95-5bab01532050.png)

## 6.1

![6 1](https://user-images.githubusercontent.com/54422211/197991604-4a4a4f72-b9e4-4aa8-99db-58fbb3693b43.png)

**Comment by ddryo** [comment]
ボタンがなくなったことはいいんですが、フロント側ではホバー時にテキストカラーが白になるのが残ってて、コアそのままのスタイルだと以下のようになるっぽい。

![CleanShot 2022-10-29 at 11 47 52](https://user-images.githubusercontent.com/31400297/198788933-7994e1ce-a99d-46d0-91c6-ceb686b2eae2.gif)

（Arkheではコアに追従するようにしててほぼその辺はCSSいじってないはず）
ちなみに、デフォルトテーマ（TT2,TT3）ではテーマ側でボタンのスタイル当ててるようなので問題なさそうだった。

 @t-hamano 
意図したものなのであればこちらで調整しますが、不具合の可能性もあるので一度issue投げお願いしたいです！

**Comment by ddryo** [comment]
取り急ぎ、バグだったとしても11/1までには治らないと思うのでボタンスタイルをテーマ側で指定。

**Comment by t-hamano** [comment]
issueを立てました。
これは、クラシックテーマ向けの後方互換対応漏れだと思います。
https://github.com/WordPress/gutenberg/issues/45399
