### ISSUE TITLE
カテゴリーブロック：エディター側のスタイル崩れ

### ISSUE THREAD

**Issue by t-hamano** [loos/arkhe#87]
https://github.com/loos/SWELL/issues/292 と同様

![category](https://user-images.githubusercontent.com/54422211/198001685-6fb068d2-696c-4ed3-b9ff-b01050ccc5fd.png)

**Comment by ddryo** [comment]
memo: 根本解決するには大規模な調整が必要か。

https://github.com/loos/SWELL/issues/302

**Comment by ddryo** [comment]
https://github.com/loos/arkhe/commit/8c6ffc9626e8f2fcec94c7976d945aa1191d6c42
